---
title: "Лабораторна робота №5"
author: "Болотнікова Милана, КІ-25-1"
date: today
lang: uk
format: html
execute:
  echo: true
  warning: false
  message: false
---

```{r}
#| label: setup
#| message: false
#| warning: false

library(knitr)
library(ggplot2)
```

```{r}
data_var2 <- data.frame(
  X = c(8.17, 5.74, 7.89, 8.38, 6.35, 7.84, 0.68, 3.84, 11.66, 6.27),
  Y = c(2775.612765, 1590.619802, 852.1152743, 741.9307833, 574.0234767, 479.3814706, 817.7464993, 1216.079125, 689.388817, 1272.771308)
)

model <- lm(Y ~ X, data = data_var2)
summary(model)

library(ggplot2)
ggplot(data_var2, aes(x = X, y = Y)) +
  geom_point() +
  geom_smooth(method = "lm")
```

```{r}
#| fig-cap: "Кореляційне поле для виявлення зв'язку"

ggplot(data_var2, aes(x = X, y = Y)) +
  geom_point(color = "#2c3e50", size = 3) +
  theme_minimal() +
  labs(title = "Кореляційне поле", x = "Вхідна змінна X", y = "Залежна змінна Y")
```

```{r}
model <- lm(Y ~ X, data = data_var2)

summary(model)
```

```{r}
anova(model)
```

```{r}
ggplot(data_var2, aes(x = X, y = Y)) +
  geom_point(color = "#2c3e50", size = 2) +
  geom_smooth(method = "lm", color = "#e74c3c", se = TRUE) +
  theme_minimal() +
  labs(title = "Апроксимація даних лінійною функцією", x = "X", y = "Y")
```

```{r}
data_var2$residuals <- residuals(model)
data_var2$predicted <- predict(model)

ggplot(data_var2, aes(x = predicted, y = residuals)) +
  geom_point(color = "#16a085", size = 2) +
  geom_hline(yintercept = 0, color = "red", linetype = "dashed") +
  theme_minimal() +
  labs(title = "Графік залишків", x = "Прогнозовані значення", y = "Залишки")
```
